// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeTCmr_ajJqvePtHh2vgiu8XMABo_yr18',
    appId: '1:289684198409:ios:bf644b34a70ee0809554d8',
    messagingSenderId: '289684198409',
    projectId: 'my-first-app-b393a',
    storageBucket: 'my-first-app-b393a.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeTCmr_ajJqvePtHh2vgiu8XMABo_yr18',
    appId: '1:289684198409:ios:bf644b34a70ee0809554d8',
    messagingSenderId: '289684198409',
    projectId: 'my-first-app-b393a',
    storageBucket: 'my-first-app-b393a.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgYK194Vqq4flKG4RZYtjHlCdHSvujpCA',
    appId: '1:289684198409:web:30c0c385967584ac9554d8',
    messagingSenderId: '289684198409',
    projectId: 'my-first-app-b393a',
    authDomain: 'my-first-app-b393a.firebaseapp.com',
    storageBucket: 'my-first-app-b393a.firebasestorage.app',
    measurementId: 'G-HZBFLSZB1X',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYK194Vqq4flKG4RZYtjHlCdHSvujpCA',
    appId: '1:289684198409:web:30c0c385967584ac9554d8',
    messagingSenderId: '289684198409',
    projectId: 'my-first-app-b393a',
    authDomain: 'my-first-app-b393a.firebaseapp.com',
    storageBucket: 'my-first-app-b393a.firebasestorage.app',
    measurementId: 'G-HZBFLSZB1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLFeFKHAQ34JwzL3WPAxLBEB843kBf5s',
    appId: '1:289684198409:android:e39fc09f965b9d5a9554d8',
    messagingSenderId: '289684198409',
    projectId: 'my-first-app-b393a',
    storageBucket: 'my-first-app-b393a.firebasestorage.app',
  );
}
